### ISSUE TITLE
SDK & dApp-Kit Certificate

### ISSUE THREAD

**Issue by rodolfopietro97** [vechain/vechain-sdk-js#1029]
Understand differences between certificates in Dappkit and in SDK.
Previously it seems that they didn't works,
currently to test that we need to solve a bug into Dappkit tests

**Comment by victhorbi** [comment]
@lucanicoladebiasi isn't this investigation done already?

**Comment by victhorbi** [comment]
@lucanicoladebiasi do we still require this investigation?
If we do, we need to change the blocker to the new connex ticket.

**Comment by lucanicoladebiasi** [comment]
No. It we don't need anymore because the circumstances of incompatibility are well known.
1. Thor-Dev-Kit doesn't enforce any normalisation encoding strings to bytes, the SDK does. There are no incompatibility if texts are part of Latin alphabets and not-Latin alphabets for those symbols standardised in same Unicode bytes sequence, but when ideograms or emoticon or glyphs are combined in a single symbol it could be different runtimes running the Thor-Dev-Kit result in different encoding, hashes, signatures and certificates.
2. Thor-Dev-Kit leverages on `ethers` in hexadecimal encoding, but some of the functions in `ethers` use regex to distinguish between hex content and text content with the result the encoding of 'caffe' is `Uint8Array.of(0xca, 0xff, 0xee)` instead of `Uint8Array.of(0x63, 0x61, 0x66, 0x66, 0x65, 0x65)`. This confusion is no more possible using the SDK where the VeChain Data Model enforces explicit casting in the code and assures the same binary representation when data are cast among compatible types.
**Thor-Dev-Kit should be deprecated the sooner.**

**Comment by lucanicoladebiasi** [comment]
In the SDK there are specific tests to check the SDK and Thor-Dev-Kit certificates are compatible for not ambiguous unicode inputs and under what circumstances the results are different if code developed with the Thor-Dev-Kit doesn't cast and encode correctly the given input.

**Comment by lucanicoladebiasi** [comment]
Obviously, if dApp-Kit depends of the Thor-Dev-Kit the problem of incompatibility could rise, but once sApp-Kit depends on the SDK, certificates are managed by SDK code in a way the same chain of transformations from input to certificate and signature and verification is controlled, enforced for correctness and tested.

**Comment by victhorbi** [comment]
Hey @lucanicoladebiasi , thor-devkit dependency was replaced with the SDK few weeks back.
We can close this ticket.
