### ISSUE TITLE
Try to substitute secp256k1 using noble-secp256k1

### ISSUE THREAD

**Issue by rodolfopietro97** [vechain/vechain-sdk-js#105]
Tasks:
- [ ] Investigate package change
- [ ] Needs to be mobile compatible
- [ ] Make branch with package change and run tests

**Comment by lucanicoladebiasi** [comment]
Done.
- It resulted convenient to rewrite the `packages/core/src/secp256k1/secp256k1.ts` using the `noble` library instead of the `elliptic` library to keep the same method signature used in the rest of the SDK.
- Private and Public key generation are completed migrated to noble, with a - roughly empiric - increase of performance of three times.

In progress.
- Writing the `sign` and `recover` methods, it presents some challenge to keep the binary compatibility in parsing and representation of what `elliptic` library provides and make the new code passes all the tests with minimal changes. I proved `noble` provides the same functionalities but with different internal mechanisms hence the element of the keys to extract and interpreter are different.

Forecast.
- I will rise in next 24 hours.
- I presume I will need 2 days of study and experimentation to deliver the whole solution.

**Comment by lucanicoladebiasi** [comment]
I have discovered issues between signatures made using the `elliptic` lib (in actual SDK) and `noble` lib, those could have different formats as described at https://gist.github.com/paulmillr/a1f221502f73d70251b2c0e77d18ee2d.
Technically, the same mathematical infos (i.e. the points of elliptic curve, aka ECDSA) should be represented in both, hence I'm hacking how to make SDK agnostic about them.
