### ISSUE TITLE
Investigate if we can support eth_signTypedData

### ISSUE THREAD

**Issue by victhorbi** [vechain/vechain-sdk-js#1327]
Here's the EIP: https://eips.ethereum.org/EIPS/eip-712

The method is becoming popular in VeBetter since it's being used for social login, in the flow pioneered by Cleanify.

**Comment by victhorbi** [comment]
@rodolfopietro97 , please sync with @vanja-vechain and @Agilulfo1820 to scope the work to do.

**Comment by rodolfopietro97** [comment]
The method is present on the signer. So now we must create the RPC eth_signTYpedData

**Comment by rodolfopietro97** [comment]
The functions eth_signTypedData_v1, v2, v3, and v4 refer to different versions of the method used in Ethereum walletsfor signing structured data. Here’s a breakdown of the differences between them:

1. **eth_signTypedData_v1**:
   * The first version that allowed signing structured data. This version relied on the message format defined by Solidity structs
   * It had limitations because it didn’t clearly separate the domain of the data from the actual message.
   * Rarely used today, as newer versions address its limitations.
2. **eth_signTypedData_v2**:
   * This version was intended to provide an improved user interface for signing data, but it wasn't widely adopted due to technical limitations. It was an experimental phase and not much documentation is available.
   * Not widely implemented or used.
3. eth_signTypedData_v3:
   * This version introduced a clear separation between the domain separator and the actual message being signed. The domain separator defines metadata like the contract address, chain ID, etc., which improves the security of the signatures. The message data is encoded using the EIP-712 standard. In this version, the data is still serialized as a JSON string (hex-encoded).
   * This version was popular for a while but was replaced by v4 for further improvements.
4. eth_signTypedData_v4:
   * This version improves upon v3 by refining how the typed data is encoded and parsed. In particular, it supports a wider variety of data types and complex nested structures as per EIP-712. It also uses a more optimized encoding for the message and domain, making the signature process more efficient.
    * v4 is the current standard used by many dApps and wallets like MetaMask.
Key Differences:
   * v4 supports more complex and nested data types than v3.
   * eth_signTypedData_v4 is the preferred method today due to its support for EIP-712 and its improvements in both performance and security.
   * It is our current signature implementaiton into signer. So the best approach is to make eth_signTypedData_v4 endpoint
