### ISSUE TITLE
🐛 [BUG] - jsdom testing environment is not supported by the sdk

### ISSUE THREAD

**Issue by davidecarpini** [vechain/vechain-sdk-js#1424]
### Description

the sdk should support also jsdom as a testing environment

```
frontend:test: TypeError: text.normalize is not a function
frontend:test:  ❯ Object.encode ../../../vechain-dapp-kit/node_modules/@vechain/sdk-core/dist/index.js:3452:12
frontend:test:     3450|   encode: function(text) {
frontend:test:     3451|     return TEXT_ENCODER.encode(
frontend:test:     3452|       text.normalize(NORMALIZATION_FORM_CANONICAL_COMPOSITION)
frontend:test:        |            ^
frontend:test:     3453|     );
frontend:test:     3454|   }
```

it works correctly with happy-dom instead

### Reproduction steps

```bash
1. Create a vitest frontend test that renders something, using SDK and jsdom
2.  you will get this error when you try to run it:

frontend:test: TypeError: text.normalize is not a function
frontend:test:  ❯ Object.encode ../../../vechain-dapp-kit/node_modules/@vechain/sdk-core/dist/index.js:3452:12
frontend:test:     3450|   encode: function(text) {
frontend:test:     3451|     return TEXT_ENCODER.encode(
frontend:test:     3452|       text.normalize(NORMALIZATION_FORM_CANONICAL_COMPOSITION)
frontend:test:        |            ^
frontend:test:     3453|     );
frontend:test:     3454|   }
```
```


### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by freemanzMrojo** [comment]
hi @davidecarpini I can see in the paths that you were working on the dapp-kit project. since it is open source, would you mind sharing a branch with this testing code so we reproduce the error from there (if it is not too inconvenient ofc)? thanks in advance!

**Comment by davidecarpini** [comment]
```yarn install:all && yarn test```
on 'test-branch-for-sdk-jsdom-error' branch of the dapp-kit and you will get the error


<img width="1039" alt="Screenshot 2024-10-22 at 16 21 53" src="https://github.com/user-attachments/assets/a5f87927-15b6-4d3d-9bbf-a5ae40c72fa2">

**Comment by fabiorigam** [comment]
Hi @davidecarpini, I see you are using version 24 of the SDK. I tried with version 32 (latest release) and I don't see issues related with SDK. There is a small one related with the type passed to a param on `src/DAppKitProvider.tsx`. Can you please update the version and let us know if there are other issues? Thanks

**Comment by davidecarpini** [comment]
just updated to the version 32, same stuff

<img width="950" alt="Screenshot 2024-10-28 at 12 30 16" src="https://github.com/user-attachments/assets/6c612ba3-e133-4834-97d7-0cebff1beb31">

**Comment by leszek-vechain** [comment]
did quick retest for rc.3:

- dapp-kit (beta.32)
- dapp-kit-react (rc.3)

![Image](https://github.com/user-attachments/assets/07bf4d75-af10-4f03-836c-cedaa210572a)

- dapp-kit (rc.3)
- dapp-kit-react (rc.3)

![Image](https://github.com/user-attachments/assets/9cc69623-8f88-43ed-a06f-c5b72935681f)

**Comment by freemanzMrojo** [comment]
I saw the notification and I wanted to share a couple of considerations:

1. The error above @leszek-vechain is because that library is not supported anymore in the release candidates, once that is adapted the error remains the same
2. The error itself is about the CommonJS bundle from the SDK used by jsdom (`index.js`, that is why it works in other contexts (`index.mjs` in ESM). So I would review precisely that bundle (the error happens because apparently `e.normalize` is not a function when e is an string)

I can look into this myself at some point too if needs be.

**Comment by freemanzMrojo** [comment]
Hey guys, I looked into it and now the tests are passing as described by @davidecarpini. The "issue" (you will see why I am quoting it) is basically as follows.

The error happens when calling the transpiled CommonJS version of this method, since it is unable to figure out that `exp` is always a `string`:

```
    protected constructor(exp: string) {
        super(exp.normalize(Txt.NFC));
    }
```

 By following the error trace, I saw that the call happened in this method:
 
 ```
     public static of(exp: bigint | number | string | Uint8Array): Txt {
        if (exp instanceof Uint8Array) {
            return new Txt(Txt.DECODER.decode(exp)); // Can find out the input parameter is a string
        } else if (typeof exp === 'bigint' || typeof exp === 'number') {
            return new Txt(exp.toString()); // Can find out the input parameter is a string
        }
        return new Txt(exp); // Cannot find out the input parameter is a string 
        // In the IDE is inferred by the checks above, but it does not work in the CommonJS version so efectively it does not know that exp is a string too.
    }
 ```
 
 This is the transpiled code representing the same (good luck reading it 😆 ):
 
 ```
 constructor(e){super(e.normalize(n.NFC));}
 ...
 
 static of(e){return e instanceof Uint8Array?new n(n.DECODER.decode(e)):typeof e=="bigint"||typeof e=="number"?new n(e.toString()):new n(e)}}
 ```
 
 By ensuring that we always pass a `string` (in the transpiled version, in TS obviously is always the case) the problem is solved.
 
 Will create a PR soon, but I think we should review more carefully how we use the SDK in CommonJS cases (for DappKit is just the `jsdom` environment in `vitest`, but what about other projects? Should we advise somehow to use ESM preferably (mjs)?
 
 Feel free to open a discussion in Slack if you think it makes sense.
 
 @victhorbi @claytonneal @lucanicoladebiasi @fabiorigam

**Comment by freemanzMrojo** [comment]
Finally it turned out to be a `vitest` issue when using `jsdom`: https://github.com/vitest-dev/vitest/issues/5183

Will create a PR anyways to see if we can avoid `instanceof Uint8Array`.

**Comment by davidecarpini** [comment]
Great work @freemanzMrojo 🔥👏
