### ISSUE TITLE
💡 [Certificate] - allow access to encoding

### ISSUE THREAD

**Issue by darrenvechain** [vechain/vechain-sdk-js#1487]
### Summary

Currently the `encode` method is not accessible on the Certificate class. The only way to sign the certificate is if I have a private key.

I may not have a private key, I could have a ledger.

### Basic Example

```typescript
const encoded = Certificate.encode(myCertData);
```

**Comment by victhorbi** [comment]
Legit, makes sense to expand the scope also to KMS.

**Comment by lucanicoladebiasi** [comment]
It is not possible to sign and verify a certificate without a public key or any hardware or software object representing indirectly a private key because the definition of SECP256K1 algorithm involved in signature and verification of data.

The "ledger" represents the private key. If as it correct, a private key can't leave the ledger and be argument of the SECP256K1, the ledger must provides SECP256K1 sign and verify methods where the certificate must be passed as argument.

The solution is to add in the file `packages/core/src/certificate/Certificate.ts` the method
```
public encode(): Uint8Array {
        return Certificate.encode({ ...this, signature: undefined });
}
```
assuring only a `Certificate` instance is encoded and the signature is stripped from the encoded bytes because sign and verify methods needs to have a binary representation of the certificate before it is signed, being the purpose of sign to add add the signature and the purpose of verify to check the content signed is what is it without its signature.
