### ISSUE TITLE
Bloom Filter :: Extend bloom to inject a block

### ISSUE THREAD

**Issue by darrenvechain** [vechain/vechain-sdk-js#369]
As a developer, I want to pass an `ExtendedBlock` into bloom so that I can check for addresses

The current bloom filter is generic and hard to use. I would propose extending it to accept an expanded block (or the outputs of an expanded block) ie.:

```typescript
const block = await blocks.getBlock("best", {expanded: true})

const bloom = new BlockBloom(block)

const isMembor = bloom.containsAddress("myAddress")

console.log(isMember)
```

**Comment by lucanicoladebiasi** [comment]
Working on branch at 
https://github.com/vechain/vechain-sdk-js/tree/369-bloom-filter-extend-bloom-to-inject-a-block

Hash functions in
* packages/core/src/hash/blake2b256.ts
* packages/core/src/hash/keccak256.ts
* packages/core/src/hash/sha256.ts
secured.

**Comment by lucanicoladebiasi** [comment]
The logic is to derive the Bloom's filter from the addresses described in the properties of `ExpandedBlockDetail` in `packages/network/src/thor-client/blocks/types.d.ts`.

The SDK should provide two methods in `packages/core/src/utils/bloom/bloom.ts` or `packages/core/src/bloom/bloom.ts`
* accepting `ExpandedBlockDetail`` and returning the Bloom's filter expression,
* accepting a Bloom's filter expression and an address returning if the address possibly belongs to the set of addresses (partially done in `packages/core/src/utils/bloom/bloom.ts`).

**Comment by lucanicoladebiasi** [comment]
For `ExpandedBlockDetail`, the properties referring addresses are 

- `beneficiary: string;`
- `signer: string;`
- `transactions: TransactionsExpandedBlockDetail[];`
   - `clauses: Clause[];`
      - `to: string | null;`
   - `delegator: string;`
   - `gasPayer: string;`
   - `origin: string;`
   - `outputs: Output[];`
      - `contractAddress: string | null;`
      - `events: Event[];`
         - ` address: string;`
      - `transfers: Transfer[];`
         - `recipient: string;`
         - `sender: string;`

**Comment by lucanicoladebiasi** [comment]
The `packages/core/src/utils/bloom/bloom.ts` provides the `filterOf` method to build the Bloom filter from any array of Thor addresses, filtering out strings those are Thor addresses (like empty strings) and duplicates to let the bloom filters to be consistent the same addresses shared by different blocks using where the addresses are values of different properties. 
However I suspect it is limiting to provide the functionality to build the Bloom filter just from a block instance, hence I extended the concept, `filterOf` accepts any array of addresses in any form, to easily combine  multiple blocks in one filter.

The method `addressesOf` scans the (extended) block for addresses, this is the helper function used to provide what required by the ticket because the solution provided is

```
bloomUtils.filterOf(bloomUtils.addressesOf(expandedBlockDetail));
```

assuming some default parameters are set, see below.

Unfortunately two Bloom filters derived by blocks are useless if the `k` (hash functions) or `m` (bits per keys) are different, those are not comparable. In our SDK the Bloom filter is just an array of bytes, it hasn't the `k` or `m` properties.
I didn't take the decision to include them to make filters to be comparable, albeit this is something is worth to think if important (and trivial) to introduce.

To test the same address against different filters from different blocks - those must have `k` and `m` in common - I introduced in `packages/core/src/bloom/bloom.ts` the function `calculateBitsPerKey` reciprocal of `calculateK` to help.

Because what above, after some mathematic experimentation, I derived k = 5 as default parameter for `filterOf` to allow the filter to compress the set of represented addresses of 20 times with a probability of collision far smaller than 1%, in average all addresses in a block of Thor solo are encoded in 14 bytes with no false positive experienced. However this assumption is related with the real number of addresses per block typical of the real Thor and I have no guess about.

However since we do not provides any mean to derive `k` and `m` from Thor addresses, and the Filter class do not represent them, to make `bloomUtil.filterOf` practically usable without math mumbling, I introduced the constant 'BLOOM_DEFAULT_K = 5` to let users to build comparable Blom filters from extended block without any knowledge of the backing math.
