### ISSUE TITLE
Remove Crypto Deprecated Package

### ISSUE THREAD

**Issue by nwbrettski** [vechain/vechain-sdk-js#725]
Remove and if necessary replace the https://www.npmjs.com/package/crypto-js package which is deprecated.

Questions:
- What do we use this package for?
- Can we replace this package / Do we need to replace this package?

**Comment by lucanicoladebiasi** [comment]
This ticket derives from the experiment I'm doing on the https://github.com/vechain/vechain-sdk-js/tree/712-derive-public-key-from-wallet-extended-public-key-without-elliptic-library.

**Comment by lucanicoladebiasi** [comment]
I share with you the rationales to make the SDK secure according the Ethereum Foundation specifications and the work to be done, considering I’m progressing in my spare time now, with big intellectual fun. I estimate I can obtain the result in the equivalent of 5-10 days full time.
 
The reasons why only audited and secure code should be used are published in the instructional paper at. https://paulmillr.com/posts/noble-secp256k1-fast-ecc/ published by Paul Miller, appointed by the Ethereum Foundation (EF) to lead the development of production grade JS libraries. Below my analysis and progress status in the experimental https://github.com/vechain/vechain-sdk-js/tree/712-derive-public-key-from-wallet-extended-public-key-without-elliptic-library of my effort to make Vechain SDK the first secure SDK to be compliant with the EF specifications. The security in the actual `main` branch vulnerabilities in bold.
 
**packages/core/src/abi/coder.ts**
AbiCoder simply manipulate bytes, it doesn’t involve cryptography, those functions can be forked by `ethers` without troubles because MIT license. Some of them are provided by https://github.com/paulmillr/scure-base. **To do**.
 
**packages/core/src/address/address.ts**
The address derives from the last 20 bytes of the KECCAK hash of the uncompressed public key. This is the only functionalities still requires the uncompressed key because addresses were imagined before to find an efficient algorithm to derive the curve’s plots from x points only, The Ethereum Foundation suggests to only manipulate compressed forms since mathematically the uncompressed forms encode the codomain y coordinates of the curves those can be always computed from domain y coordinates. `ethers` have vulnerabilities related with its internal use of deprecated `elliptic` library. After some studies to avoid overflows in JS runtime, the code I propose based on Miller’s work is…
```
import { Point } from 'noble-secp256k1';
 
// Function to derive uncompressed public key from compressed public key
function deriveUncompressedPublicKey(compressedKey: Buffer): Buffer {
    // Parse the compressed public key
    const compressedPoint = Point.fromHex(Hex.of(compressedKey));
 
    // Decompress the public key
    const uncompressedPoint = compressedPoint.decompress();
 
    // Return uncompressed public key
    return Buffer.from(uncompressedPoint.toHex(), 'hex');
}
```
**In progress.**
 
**packages/core/src/hash/keccak256.ts
packages/core/src/hash/sha256.ts`**
SHA-3 / KECCAK are not secure in `ethers. The library https://github.com/paulmillr/noble-hashes provides `secure hash` functions to do the same. **Done.**
 
**packages/core/src/keystore/keystore.ts**
Ether implementation is based on the deprecated crypto, those functions are equivalent to what provided by https://github.com/paulmillr/noble-curves. The rest of the code is based on JSON and file handling, JSON formats are described and can be replicated. I did myself a keystore for Ethereum in 2019. **To do.**
 
**packages/core/src/mnemonic/mnemonic.ts**
Functionalities provided by secured algorithm by https://github.com/paulmillr/scure-bip39. **Done.**
 
**packages/core/src/utils/data/data.ts**
The same data transformations – trivial – are provided by https://github.com/paulmillr/scure-base. **To do.**
 
**packages/core/src/utils/units/units.ts**
`ethers.parseUnit` can be forked and replicated trivially. **To do.**
 
**packages/core/tests/abi/contract.unit.test.ts**
Use of `new ethers.Interface` to test contract representations, this doesn’t infringe security and the library can be used for tests without danger.
 
**packages/core/tests/hash/hash.unit.test.ts**
The same functionalities are provided by https://github.com/paulmillr/scure-base., nevertheless I suggest keeping `ethers` for doesn’t harm and proves the secure libraries are really providing the same.

**Comment by nwbrettski** [comment]
@lucanicoladebiasi a couple of follow up questions on this.

- Can you provide some suggestions on how we could test these changes?
- Will any of these changes result in further downstream changes?
- Should these changes be audited and third party tested before being incorporated into the SDK?

**Comment by lucanicoladebiasi** [comment]
> [@lucanicoladebiasi](https://github.com/lucanicoladebiasi) a couple of follow up questions on this.
> 
> * Can you provide some suggestions on how we could test these changes?
> * Will any of these changes result in further downstream changes?
> * Should these changes be audited and third party tested before being incorporated into the SDK?

* Without changing tests, all what in place should work proving the math still is valid. In the reality, I check all the tests comparing and implementing the 'test vectors' i.e. the input and the output expected suggested my the certification authorities audited the library I used.
* Possibly yes For example many operations like converting between Buffer and Uint8Array are totally useless, should be avoided and requires the browser import libraries to make the runtime to be compatible with nodejs.
* Every function I reworked because impacting security is documented about what lib components are used, their security audit, how it is used in the function and why. This should be sufficient to provide the user the confidence we are implementing the right way because our code is published as it is of the libraries I use.  In all cases, if the cost is reasonable, I suggest when we are ready, we ask independent authorities to audit our SDK.

**Comment by lucanicoladebiasi** [comment]
Using only

```
import { secp256k1 as ec } from '@noble/curves/secp256k1';
```

The proved browser/nodejs agnostic method to inflate a public key from compressed form is to leverage of elliptic curves affinity point math, as
```
function inflatePublicKey(publicKey: Uint8Array): Uint8Array {
    const prefix = publicKey.at(0);
    if (prefix !== 4) {
        // To inflate.
        const x = publicKey.slice(0, 33);
        const p = ec.ProjectivePoint.fromAffine(
            ec.ProjectivePoint.fromHex(Hex.of(x)).toAffine()
        );
        return p.toRawBytes(false);
    } else {
        // Inflated.
        return publicKey;
    }
}
```

(Despite the solution is fast and compact, I spent days to find the right way studying what a projective point is.)

**Comment by lucanicoladebiasi** [comment]
### On Certification in the Software Industry: More Traces, Same Tests. 
- Extreme Programming - originated the practice of Unit Tests (UT) - name 'extreme' as the boundaries of the mathematic sets 'domain' and 'co-domain' the tested function maps each element of the domain is none, one or more elements in the codomain. Unit tests ideally test the extremes: when a function is expected to throw an exception, from what to what it works as designed.
- The concept of UT has two limits, too often ignored.
-  * The first one is UT guards against expected behaviours, but unfortunately most of SW bugs have origin because unexpected. UT codes according prediction, but what is unknown it is unknown - this is the phantom menace of those doing something new - can be predicted because unknown. Example: I didn't know I should have known JS bigint in an expression I coded could have lead to a numeric overflow despite it seemed to me this wasn't possible.
-  * The second problem is because UT needsIto know the expected (co-domain) results for inputs (domain), I could code tests as a big if-then-else structure: if input[n] then return expected[n], and the tests will succeed.
-  Since UT needs the domain of valid/invalid inputs and the codomain of expected results, when standard are published those are related with published 'vector tests' relating the required input and expected output to be tested. For example see at https://github.com/ethereum/tests, https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki#user-content-Test_vectors. To be certified the SW needs to provide and pass those tests.
- But since what I wrote above, tests are not sufficient because those can be fakes/forged and because some conditions at the runtime can lead to bugs (as bigint overflow conditions, or conversions between Buffer and UInt8Array) hence two things are needed:
- * The tested code must be published or al least accessible to the certification authorities. Ideally all libraries used should be open source and in life/business critical software everything is compiled from source. To import a compiled code from a lib repo is not acceptable as a big risk.
- * The code must be documented showing what is used, how and why, that means the library used must be documented, the source referred, their certifications quoted, the developers must know the code the libraries they use.
- * The above rationales and examples explain why the certification processes (as https://en.wikipedia.org/wiki/ISO_9000) stress not only about tests but about the traceability of how and why the software is designed, developed and runs. For this reason, for each security critical function I add or I plan to add a rich set of documentation explaining what I use as imported library, why and where the security certifications are published, implementing the test-vectors in UT.

**Comment by lucanicoladebiasi** [comment]
In the following comments and code commits I will use the expressions:
- **pure** to qualify code in TS is agnostic if running in node.js or any JS runtime implementation.
- **secure** if I can defend the implementation in a secure audit.

The whole hashing package is pure and secure, working on a new implementation of the bloom filter pure and secure.

**Comment by lucanicoladebiasi** [comment]
`packages/core/src/secp256k1/secp256k1.ts` pure and secure. **Done.**
